project:
  type: website
  output-dir: docs

website:
  title: "Aurelien Callens"
  site-url: https://aureliencallens.github.io/
  google-analytics: "G-MBB7RWKF8X"
  navbar:
    right:
      - text: "Projects"
        href: projects/index.qmd
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/AurelienCallens/AurelienCallens
  back-to-top-navigation: true
  page-footer:
    right:  
      - Aurélien Callens • © 2024 
    center:
      - icon: github
        href: https://github.com/AurelienCallens/AurelienCallens
      - icon: linkedin
        href: https://github.com/AurelienCallens/AurelienCallens
      - icon: envelope-fill
        href: "mailto:aurelien.callens@gmail.com"
      
  favicon: img/favicon.ico
format:
  html:
    theme: 
    - flatly
    - assets/theme.scss
    css: styles.css




