project:
  type: website

website:
  title: "Aurelien Callens"
  site-url: https://aureliencallens.github.io/
  cookie-consent: true
  google-analytics: "G-MBB7RWKF8X"
  favicon: img/favicon.ico
  back-to-top-navigation: true
  page-footer:
    center:
      - Aurélien Callens • © 2025

format:
  html:
    theme: 
    - flatly
    - assets/theme.scss
    css: styles.css

profile:
  default: fr
  group: 
    - [en, fr]