project:
  type: website
  output-dir: docs

website:
  title: "Aurelien Callens"
  site-url: https://aureliencallens.github.io/
  cookie-consent: true
  google-analytics: "G-MBB7RWKF8X"
  favicon: img/favicon.ico
  back-to-top-navigation: true
  page-footer:
    center:
      - Aurélien Callens • © 2025

format:
  html:
    theme: 
    - flatly
    - assets/theme.scss
    css: styles.css


babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: fr
    text: "French"
  - name: en
    text: "Anglais"
  mainlanguage: 'en'
  languages: ['fr']
title-fr: Aurélien Callens
description-fr: 
author-fr: Aurélien Callens
lang: en
