project:
  output-dir: docs/en
website:
    navbar:
      background: primary
      right:
        - icon: globe 
          menu:
            - text: "English"
              href: ../en/index.html
            - text: "French"
              href: ../index.html
        - href: blog.qmd
        - href: myprojects.qmd
        - icon: github
          href: https://github.com/AurelienCallens
