name: quarto
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - anyio=4.2.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attrs=23.2.0
  - aws-c-auth=0.7.14
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.3
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.5.0
  - aws-c-sdkutils=0.1.14
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.1
  - aws-sdk-cpp=1.11.242
  - azure-core-cpp=1.10.3
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - binutils_impl_linux-64=2.40
  - bleach=6.1.0
  - blosc=1.21.5
  - branca=0.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.25.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfitsio=4.3.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - contourpy=1.2.0
  - curl=8.5.0
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.50.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.2.0
  - gdk-pixbuf=2.42.10
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - gfortran_impl_linux-64=13.2.0
  - ghostscript=10.02.1
  - giflib=5.2.1
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - graphviz=9.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=13.2.0
  - harfbuzz=8.3.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - imageio=2.34.0
  - imagemagick=7.1.1_27
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.29.0
  - ipyleaflet=0.18.2
  - ipython=8.20.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jbig=2.1
  - jedi=0.19.1
  - jinja2=3.1.3
  - json-c=0.17
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.2
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - kealib=1.5.3
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libarrow=14.0.2
  - libarrow-acero=14.0.2
  - libarrow-dataset=14.0.2
  - libarrow-substrait=14.0.2
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgd=2.3.3
  - libgdal=3.8.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.60.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.26
  - libparquet=14.0.2
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.25.1
  - libre2-11=2023.06.02
  - librsvg=2.56.3
  - librttopo=1.1.0
  - libsanitizer=13.2.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libudunits2=2.2.28
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.4
  - libzip=1.10.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.3
  - markupsafe=2.1.4
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - minizip=4.0.4
  - mistune=3.0.2
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.14.2
  - nbconvert-core=7.14.2
  - nbconvert-pandoc=7.14.2
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nlopt=2.7.1
  - notebook=7.0.7
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.97
  - numpy=1.26.3
  - openjpeg=2.5.0
  - openssl=3.2.1
  - orc=1.9.2
  - overrides=7.6.0
  - packaging=23.2
  - pandas=2.2.0
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.42
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.2
  - pixman=0.43.0
  - pkg-config=0.29.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - plotly=5.18.0
  - poppler=23.12.0
  - poppler-data=0.4.12
  - postgresql=16.1
  - proj=9.3.1
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.4
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - r-abind=1.4_5
  - r-arrow=14.0.1
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.3.2
  - r-base64enc=0.1_3
  - r-binman=0.1.3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-boot=1.3_28.1
  - r-broom=1.0.5
  - r-bslib=0.6.1
  - r-cachem=1.0.8
  - r-callr=3.7.3
  - r-car=3.1_2
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-catools=1.18.2
  - r-cellranger=1.1.0
  - r-checkmate=2.3.0
  - r-class=7.3_22
  - r-classint=0.4_10
  - r-cli=3.6.2
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-cluster=2.1.6
  - r-codetools=0.2_19
  - r-colorspace=2.1_0
  - r-commonmark=1.9.0
  - r-conflicted=1.2.0
  - r-conquer=1.3.3
  - r-corrplot=0.92
  - r-cowplot=1.1.3
  - r-cpp11=0.4.7
  - r-crayon=1.5.2
  - r-crosstalk=1.2.1
  - r-crul=1.4.0
  - r-curl=5.1.0
  - r-data.table=1.14.10
  - r-dbi=1.2.1
  - r-dbplyr=2.4.0
  - r-diagram=1.6.5
  - r-digest=0.6.34
  - r-dplyr=1.1.4
  - r-dtplyr=1.3.1
  - r-e1071=1.7_14
  - r-ellipsis=0.3.2
  - r-essentials=4.3
  - r-evaluate=0.23
  - r-fansi=1.0.6
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_86
  - r-formatr=1.14
  - r-fs=1.6.3
  - r-furrr=0.3.1
  - r-future=1.33.1
  - r-future.apply=1.11.1
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-ggplot2=3.4.4
  - r-ggpubr=0.6.0
  - r-ggrepel=0.9.5
  - r-ggsci=3.0.0
  - r-ggsignif=0.6.4
  - r-gistr=0.9.0
  - r-glmnet=4.1_8
  - r-globals=0.16.2
  - r-glue=1.7.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gridextra=2.3
  - r-gtable=0.3.4
  - r-hardhat=1.3.0
  - r-haven=2.5.4
  - r-hexbin=1.28.3
  - r-highr=0.10
  - r-hms=1.1.3
  - r-htmltools=0.5.7
  - r-htmlwidgets=1.6.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.13
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-igraph=1.5.1
  - r-ipred=0.9_14
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.8
  - r-kernsmooth=2.23_22
  - r-knitr=1.45
  - r-labeling=0.4.3
  - r-later=1.3.2
  - r-lattice=0.22_5
  - r-lava=1.7.3
  - r-lazyeval=0.2.2
  - r-leaflet=2.2.1
  - r-leaflet.providers=2.0.0
  - r-lifecycle=1.0.4
  - r-listenv=0.9.0
  - r-lme4=1.1_35.1
  - r-lobstr=1.1.2
  - r-lubridate=1.9.3
  - r-magick=2.8.2
  - r-magrittr=2.0.3
  - r-maps=3.4.2
  - r-maptools=1.1_8
  - r-markdown=1.12
  - r-mass=7.3_60
  - r-matrix=1.6_5
  - r-matrixmodels=0.5_3
  - r-matrixstats=1.2.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-minqa=1.2.6
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.0
  - r-nlme=3.1_164
  - r-nloptr=2.0.3
  - r-nnet=7.3_19
  - r-numderiv=2016.8_1.1
  - r-openssl=2.1.1
  - r-pander=0.6.5
  - r-parallelly=1.36.0
  - r-pbdzmq=0.3_11
  - r-pbkrtest=0.5.2
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polynom=1.4_1
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.3
  - r-prodlim=2023.08.28
  - r-progress=1.2.3
  - r-progressr=0.14.0
  - r-promises=1.2.1
  - r-proxy=0.4_27
  - r-pryr=0.1.6
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-quantmod=0.4.25
  - r-quantreg=5.97
  - r-r.methodss3=1.8.2
  - r-r.oo=1.26.0
  - r-r.utils=2.12.3
  - r-r6=2.5.1
  - r-ragg=1.2.7
  - r-randomforest=4.7_1.1
  - r-rappdirs=0.3.3
  - r-rapportools=1.1
  - r-raster=3.6_26
  - r-rbokeh=0.5.2
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-rcpparmadillo=0.12.6.4.0
  - r-rcppeigen=0.3.3.9.4
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-recipes=1.0.9
  - r-recommended=4.3
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-repr=1.1.6
  - r-reprex=2.1.0
  - r-reshape2=1.4.4
  - r-rio=1.0.1
  - r-rlang=1.1.3
  - r-rmarkdown=2.25
  - r-rnaturalearth=1.0.1
  - r-rpart=4.1.23
  - r-rselenium=1.7.9
  - r-rstatix=0.7.2
  - r-rstudioapi=0.15.0
  - r-rvest=1.0.3
  - r-s2=1.1.6
  - r-sass=0.4.8
  - r-scales=1.3.0
  - r-selectr=0.4_2
  - r-semver=0.2.0
  - r-sf=1.0_15
  - r-shape=1.4.6
  - r-shiny=1.8.0
  - r-sourcetools=0.1.7_1
  - r-sp=2.1_3
  - r-sparsem=1.81
  - r-spatial=7.3_17
  - r-squarem=2021.1
  - r-statmod=1.5.0
  - r-stringi=1.8.3
  - r-stringr=1.5.1
  - r-summarytools=1.0.1
  - r-survival=3.5_7
  - r-sys=3.4.2
  - r-systemfonts=1.0.5
  - r-terra=1.7_71
  - r-textshaping=0.3.7
  - r-tibble=3.2.1
  - r-tidygeocoder=1.0.5
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.0
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4032.109
  - r-tinytex=0.49
  - r-triebeard=0.4.1
  - r-ttr=0.24.4
  - r-tzdb=0.4.0
  - r-units=0.8_5
  - r-urltools=1.7.3
  - r-utf8=1.2.4
  - r-uuid=1.2_0
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-visnetwork=2.1.2
  - r-vroom=1.6.5
  - r-wdman=0.2.6
  - r-withr=3.0.0
  - r-wk=0.9.1
  - r-writexl=1.4.2
  - r-xfun=0.41
  - r-xml=3.99_0.16.1
  - r-xml2=1.3.6
  - r-xtable=1.8_4
  - r-xts=0.13.2
  - r-yaml=2.3.8
  - r-zoo=1.8_12
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.32.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.17.1
  - s2n=1.4.3
  - scipy=1.12.0
  - sed=4.8
  - send2trash=1.8.2
  - setuptools=69.0.3
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.44.2
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - sysroot_linux-64=2.12
  - tenacity=8.2.3
  - terminado=0.18.0
  - tiledb=2.19.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - tktable=2.10
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.14.1
  - traittypes=0.2.1
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzcode=2024a
  - tzdata=2023d
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.7
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - wordcloud=1.9.3
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - radian==0.6.11
      - rchitect==0.4.6
variables:
  QUARTO_PYTHON: /home/aurelien/miniforge3/envs/quarto/bin/python3
  R_HOME: /home/aurelien/miniforge3/envs/quarto/lib/R
